name: CI (Build & Publish)

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.gitignore'

env:
  CARVEL_PKG_NAME: watchdog-graphql.local.com
  REACTOR_REPO: mitul01/watchdog-reactor

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Install Carvel Tool
        shell: bash
        run: |
          wget -O- https://carvel.dev/install.sh > install.sh
          chmod a+x ./install.sh
          sudo bash install.sh

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mitul01
          password: ${{ secrets.PAT }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Push generated package to another repository
        if: steps.semantic.outputs.new_release_published == 'true'
        shell: bash
        run: |
          git config --global user.name 'DevOpsBot'
          git config --global user.email 'devops-bot@users.noreply.github.com'
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/${{ env.REACTOR_REPO }}
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ env.REACTOR_REPO }}
          cp -r packaging/carvel-artifacts/packages/${{ env.CARVEL_PKG_NAME }}/. watchdog-reactor/packages/${{ env.CARVEL_PKG_NAME }}/${{ steps.semantic.outputs.new_release_version }}/
          cd watchdog-reactor
          git add .
          git commit -m "chore(publish-package): ${{ env.CARVEL_PKG_NAME }}:${{ steps.semantic.outputs.new_release_version }}"
          git push origin