name: Publish Carvel Package
on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs: 
  dispatch-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Extract Git Metadata
      shell: bash
      run: |
        echo "SHA_TAG=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

    - name: Repository Dispatch to watchdog-config
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: mitul01/watchdog-config
        event-type: publish-pkg
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ env.SHA_TAG }}", "app_name": "watchdog-graphql", "image": "${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.SHA_TAG}}", "version": "0.0.1" }'
    
